source 'https://rubygems.org'

ruby '2.4.0'

gem 'http'
gem 'rake', '~> 12.0.0'
gem 'nokogiri'

group :test do
  gem 'coveralls', require: false
  gem 'webmock', '~>3.0.1'
  gem 'rspec', '~> 3.6.0'
end
